import { LabelTemplate } from '../types/label';

export const DEFAULT_TEMPLATES: LabelTemplate[] = [
  {
    id: 'tpl-phone-pro-50x30',
    name: 'Tem Điện thoại Flagship (50x30 mm)',
    description: 'Mẫu tem chuẩn cửa hàng điện thoại bao gồm QR, IMEI, Model, Dung lượng, Màu sắc, Giá niêm yết.',
    category: 'phone',
    widthMm: 50,
    heightMm: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      MaMay: 'IP15P-256-NT',
      Model: 'iPhone 15 Pro Max',
      DungLuong: '256GB',
      MauSac: 'Titan Tự Nhiên',
      IMEI: '356782091234561',
      Serial: 'F2LXK982P01',
      Gia: 28990000,
      BaoHanh: '12Th',
      TenShop: 'MOBILE CITY',
    },
    elements: [
      {
        id: 'header-bg',
        type: 'rectangle',
        name: 'Header Banner',
        x: 0,
        y: 0,
        width: 50,
        height: 5.5,
        rotation: 0,
        zIndex: 1,
        fillColor: '#1e293b',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      {
        id: 'shop-title',
        type: 'text',
        name: 'Tên Shop',
        x: 2,
        y: 1,
        width: 46,
        height: 4,
        rotation: 0,
        zIndex: 2,
        content: '{{TenShop}} • GENUINE PHONE',
        fontSize: 7,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#ffffff',
      },
      {
        id: 'model-title',
        type: 'text',
        name: 'Tên Máy',
        x: 2,
        y: 6.5,
        width: 32,
        height: 4,
        rotation: 0,
        zIndex: 3,
        content: '{{Model}}',
        fontSize: 8.5,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#0f172a',
      },
      {
        id: 'specs-info',
        type: 'text',
        name: 'Thông số',
        x: 2,
        y: 10.5,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 4,
        content: 'Dung lượng: {{DungLuong}} | Màu: {{MauSac}}',
        fontSize: 6,
        fontFamily: 'sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#475569',
      },
      {
        id: 'imei-info',
        type: 'text',
        name: 'IMEI Text',
        x: 2,
        y: 14,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 5,
        content: 'IMEI: {{IMEI}}',
        fontSize: 6,
        fontFamily: 'monospace',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#0f172a',
      },
      {
        id: 'price-text',
        type: 'text',
        name: 'Giá Tiền',
        x: 2,
        y: 18,
        width: 32,
        height: 5,
        rotation: 0,
        zIndex: 6,
        content: 'GIÁ: {{Gia | currency}}',
        fontSize: 9,
        fontFamily: 'sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#dc2626',
      },
      {
        id: 'warranty-text',
        type: 'text',
        name: 'Bảo Hành',
        x: 2,
        y: 23.5,
        width: 32,
        height: 3,
        rotation: 0,
        zIndex: 7,
        content: 'BH: {{BaoHanh}} | S/N: {{Serial}}',
        fontSize: 5.5,
        fontFamily: 'sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#64748b',
      },
      {
        id: 'qr-code-main',
        type: 'qr',
        name: 'Mã QR Kiểm Tra',
        x: 34,
        y: 6.5,
        width: 14,
        height: 14,
        rotation: 0,
        zIndex: 8,
        content: 'https://check.shop.com/imei/{{IMEI}}',
        qrType: 'imei',
        fgColor: '#0f172a',
        bgColor: '#ffffff',
        errorCorrection: 'M',
      },
      {
        id: 'barcode-bottom',
        type: 'barcode',
        name: 'Mã Vạch Quét Kho',
        x: 34,
        y: 21,
        width: 14,
        height: 8,
        rotation: 0,
        zIndex: 9,
        content: '{{MaMay}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: false,
        fontSize: 10,
        fontFamily: 'monospace',
      },
      {
        id: 'divider-line',
        type: 'line',
        name: 'Phân cách',
        x: 2,
        y: 17.5,
        width: 32,
        height: 0.2,
        rotation: 0,
        zIndex: 10,
        fillColor: '#cbd5e1',
        strokeColor: '#cbd5e1',
        strokeWidth: 0.3,
      },
    ],
  },
  {
    id: 'tpl-thermal-40x30-dual',
    name: 'Tem In Nhiệt Barcode (40x30 mm - 2 Tem/Hàng)',
    description: 'Mẫu tem chuẩn cuộn in nhiệt 40x30mm 2 tem 1 hàng: Tên công ty/Shop, Barcode 12345678 và Website/Giá.',
    category: 'accessory',
    widthMm: 40,
    heightMm: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      TenShop: 'Công ty Tuki.vn',
      MaMay: '12345678',
      Website: 'tuki.vn',
      Model: 'Phụ Kiện Điện Thoại',
      Gia: 150000,
    },
    elements: [
      {
        id: 'thermal-company-title',
        type: 'text',
        name: 'Tên Công Ty / Shop',
        x: 1,
        y: 1.5,
        width: 38,
        height: 4.5,
        rotation: 0,
        zIndex: 1,
        content: '{{TenShop}}',
        fontSize: 8.5,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
      },
      {
        id: 'thermal-barcode',
        type: 'barcode',
        name: 'Mã Vạch Sản Phẩm',
        x: 2,
        y: 6.5,
        width: 36,
        height: 14,
        rotation: 0,
        zIndex: 2,
        content: '{{MaMay}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true,
        fontSize: 8.5,
        fontFamily: 'monospace',
      },
      {
        id: 'thermal-website',
        type: 'text',
        name: 'Website / Footer',
        x: 1,
        y: 22,
        width: 38,
        height: 4,
        rotation: 0,
        zIndex: 3,
        content: 'Website: {{Website}}',
        fontSize: 7,
        fontFamily: 'sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#0f172a',
      },
    ],
  },
  {
    id: 'tpl-accessory-40x30',
    name: 'Tem Phụ Kiện Compact (40x30 mm)',
    description: 'Thiết kế nhỏ gọn cho cáp sạc, tai nghe, ốp lưng với Barcode và QR Code quét giá.',
    category: 'accessory',
    widthMm: 40,
    heightMm: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      MaMay: 'PK-ANKER-65W',
      Model: 'Củ Sạc Anker GaN 65W',
      Serial: 'ANK65W00921',
      Gia: 890000,
    },
    elements: [
      {
        id: 'acc-title',
        type: 'text',
        name: 'Tên Sản Phẩm',
        x: 1,
        y: 1.5,
        width: 38,
        height: 4,
        rotation: 0,
        zIndex: 1,
        content: '{{Model}}',
        fontSize: 8,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#0f172a',
      },
      {
        id: 'acc-barcode',
        type: 'barcode',
        name: 'Barcode Phụ Kiện',
        x: 3,
        y: 6,
        width: 34,
        height: 11,
        rotation: 0,
        zIndex: 2,
        content: '{{MaMay}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true,
        fontSize: 8,
        fontFamily: 'monospace',
      },
      {
        id: 'acc-price',
        type: 'text',
        name: 'Giá',
        x: 1,
        y: 18,
        width: 25,
        height: 5,
        rotation: 0,
        zIndex: 3,
        content: '{{Gia | currency}}',
        fontSize: 10,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#2563eb',
      },
      {
        id: 'acc-sn',
        type: 'text',
        name: 'Serial Number',
        x: 1,
        y: 23.5,
        width: 25,
        height: 3,
        rotation: 0,
        zIndex: 4,
        content: 'S/N: {{Serial}}',
        fontSize: 6,
        fontFamily: 'monospace',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#64748b',
      },
      {
        id: 'acc-qr',
        type: 'qr',
        name: 'QR Quét Thông Tin',
        x: 27,
        y: 18,
        width: 11,
        height: 11,
        rotation: 0,
        zIndex: 5,
        content: '{{MaMay}}',
        qrType: 'text',
        fgColor: '#0f172a',
        bgColor: '#ffffff',
        errorCorrection: 'M',
      },
    ],
  },
  {
    id: 'tpl-vietqr-58x40',
    name: 'Tem VietQR Thanh Toán Nhanh (58x40 mm)',
    description: 'In tem dán quầy thu ngân hoặc sản phẩm cho phép khách chuyển khoản VietQR tự động điền số tiền.',
    category: 'phone',
    widthMm: 58,
    heightMm: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      Model: 'iPhone 15 Pro Max 256GB',
      Gia: 28990000,
      IMEI: '356782091234561',
      TenShop: 'MOBILE STORE',
      STK: '190388888888',
      NganHang: 'Techcombank',
    },
    elements: [
      {
        id: 'vqr-bg',
        type: 'rectangle',
        name: 'Background',
        x: 0,
        y: 0,
        width: 58,
        height: 40,
        rotation: 0,
        zIndex: 1,
        fillColor: '#f8fafc',
        strokeColor: '#e2e8f0',
        strokeWidth: 0.3,
      },
      {
        id: 'vqr-header',
        type: 'text',
        name: 'Header QR',
        x: 2,
        y: 2,
        width: 32,
        height: 4,
        rotation: 0,
        zIndex: 2,
        content: 'QUÉT VIETQR THANH TOÁN',
        fontSize: 7.5,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1e40af',
      },
      {
        id: 'vqr-model',
        type: 'text',
        name: 'Sản phẩm',
        x: 2,
        y: 7,
        width: 32,
        height: 4,
        rotation: 0,
        zIndex: 3,
        content: '{{Model}}',
        fontSize: 7,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#0f172a',
      },
      {
        id: 'vqr-price',
        type: 'text',
        name: 'Số tiền',
        x: 2,
        y: 12,
        width: 32,
        height: 6,
        rotation: 0,
        zIndex: 4,
        content: '{{Gia | currency}}',
        fontSize: 11,
        fontFamily: 'sans-serif',
        fontWeight: '800',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#dc2626',
      },
      {
        id: 'vqr-imei',
        type: 'text',
        name: 'Cú pháp CK',
        x: 2,
        y: 19,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 5,
        content: 'Nội dung: TT {{IMEI}}',
        fontSize: 6,
        fontFamily: 'monospace',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#334155',
      },
      {
        id: 'vqr-bank',
        type: 'text',
        name: 'Ngân hàng',
        x: 2,
        y: 23,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 6,
        content: 'NH: {{NganHang}} - {{STK}}',
        fontSize: 5.5,
        fontFamily: 'sans-serif',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#64748b',
      },
      {
        id: 'vqr-qr',
        type: 'qr',
        name: 'Mã VietQR Code',
        x: 35,
        y: 2,
        width: 21,
        height: 21,
        rotation: 0,
        zIndex: 7,
        content: '00020101021238580010A0000007270126000697040701121903888888880208QRIBFTTA53037045408{{Gia}}5802VN62150811TT{{IMEI}}6304',
        qrType: 'json',
        fgColor: '#0284c7',
        bgColor: '#ffffff',
        errorCorrection: 'M',
      },
      {
        id: 'vqr-footer',
        type: 'text',
        name: 'Footer',
        x: 2,
        y: 35,
        width: 54,
        height: 3,
        rotation: 0,
        zIndex: 8,
        content: 'Cảm ơn quý khách! Vui lòng kiểm tra kỹ IMEI trước khi rời cửa hàng.',
        fontSize: 5,
        fontFamily: 'sans-serif',
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#94a3b8',
      },
    ],
  },
  {
    id: 'tpl-warehouse-70x50',
    name: 'Tem Kho Dual IMEI & Barcode (70x50 mm)',
    description: 'Tem dán hộp kho quản lý IMEI 1, IMEI 2, Mã máy và Barcode đôi cho bộ phận Logistic.',
    category: 'warehouse',
    widthMm: 70,
    heightMm: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      Model: 'iPhone 15 Pro Max 256GB Titan',
      IMEI: '356782091234561',
      Serial: 'F2LXK982P01',
      MaKho: 'KHO-HN-01',
      Gia: 28990000,
    },
    elements: [
      {
        id: 'wh-header',
        type: 'text',
        name: 'Header Kho',
        x: 2,
        y: 2,
        width: 66,
        height: 4,
        rotation: 0,
        zIndex: 1,
        content: 'TEM QUẢN LÝ KHO & BẢO HÀNH - {{MaKho}}',
        fontSize: 8,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#0f172a',
      },
      {
        id: 'wh-model',
        type: 'text',
        name: 'Model',
        x: 2,
        y: 7,
        width: 48,
        height: 4,
        rotation: 0,
        zIndex: 2,
        content: 'Tên Máy: {{Model}}',
        fontSize: 8,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1e293b',
      },
      {
        id: 'wh-barcode1',
        type: 'barcode',
        name: 'Barcode IMEI',
        x: 2,
        y: 12,
        width: 48,
        height: 12,
        rotation: 0,
        zIndex: 3,
        content: '{{IMEI}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true,
        fontSize: 8,
        fontFamily: 'monospace',
      },
      {
        id: 'wh-barcode2',
        type: 'barcode',
        name: 'Barcode Serial',
        x: 2,
        y: 26,
        width: 48,
        height: 12,
        rotation: 0,
        zIndex: 4,
        content: '{{Serial}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true,
        fontSize: 8,
        fontFamily: 'monospace',
      },
      {
        id: 'wh-qr',
        type: 'qr',
        name: 'QR Kho',
        x: 52,
        y: 12,
        width: 16,
        height: 16,
        rotation: 0,
        zIndex: 5,
        content: 'KHO:{{MaKho}}|IMEI:{{IMEI}}|SN:{{Serial}}',
        qrType: 'text',
        fgColor: '#000000',
        bgColor: '#ffffff',
        errorCorrection: 'M',
      },
      {
        id: 'wh-price',
        type: 'text',
        name: 'Giá Nhập/Bán',
        x: 2,
        y: 42,
        width: 66,
        height: 5,
        rotation: 0,
        zIndex: 6,
        content: 'GIÁ NIÊM YẾT: {{Gia | currency}}',
        fontSize: 9.5,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#b91c1c',
      },
    ],
  },
  {
    id: 'tpl-2col-model-serial-50x30',
    name: 'Tem 2 Cột chuẩn (Model & Serial - 50x30 mm)',
    description: 'Mẫu tem tối giản chỉ gồm 2 cột Model và Serial. Tải file Excel mẫu sẽ tự động xuất đúng 2 cột.',
    category: 'phone',
    widthMm: 50,
    heightMm: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sampleData: {
      Model: 'iPhone 15 Pro Max 256GB',
      Serial: 'F2LXK982P01',
    },
    elements: [
      {
        id: '2col-header-bg',
        type: 'rectangle',
        name: 'Khung Khung',
        x: 1,
        y: 1,
        width: 48,
        height: 28,
        rotation: 0,
        zIndex: 1,
        fillColor: '#f8fafc',
        strokeColor: '#cbd5e1',
        strokeWidth: 0.5,
      },
      {
        id: '2col-model-title',
        type: 'text',
        name: 'Model Sản Phẩm',
        x: 3,
        y: 3,
        width: 44,
        height: 6,
        rotation: 0,
        zIndex: 2,
        content: '{{Model}}',
        fontSize: 10,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#0f172a',
      },
      {
        id: '2col-barcode-serial',
        type: 'barcode',
        name: 'Barcode Serial',
        x: 4,
        y: 10,
        width: 42,
        height: 12,
        rotation: 0,
        zIndex: 3,
        content: '{{Serial}}',
        format: 'CODE128',
        fgColor: '#000000',
        bgColor: '#ffffff',
        displayValue: true,
        fontSize: 8,
        fontFamily: 'monospace',
      },
      {
        id: '2col-serial-text',
        type: 'text',
        name: 'Mã Serial',
        x: 3,
        y: 23,
        width: 44,
        height: 4,
        rotation: 0,
        zIndex: 4,
        content: 'S/N: {{Serial}}',
        fontSize: 7.5,
        fontFamily: 'monospace',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#334155',
      },
    ],
  },
];

